version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: clearchoice
    environment:
      POSTGRES_USER: clear1choice
      POSTGRES_PASSWORD: testpass123
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: